##PVT LMMs ##
PVT <- read_excel("GitStuff/mswake/Main-results/PVT_results.xlsx")
PVT$Sex=factor(PVT$Sex)
PVT$Weight=factor(PVT$Weight)
PVT$Time=factor(PVT$Time)
PVT<- PVT %>% filter(Condition=="W")
pvtrs_lm <- lmer(mean_rs ~ Time*Sex + Time*Weight + (1|sub), data=PVT,REML=TRUE)
pvtslowrs_lm <- lmer(slowest_rs ~ Time*Sex + Time*Weight + (1|sub), data=PVT,REML=TRUE)
pvtrsb_lm <- lmer(rs_basner ~ Time*Sex + Time*Weight + (1|sub), data=PVT,REML=TRUE)
pvtslowrsb_lm <- lmer(slowrs_basner ~ Time*Sex + Time*Weight + (1|sub), data=PVT,REML=TRUE)
lapses_lm <- lmer(Total_lapse ~ Time*Sex + Time*Weight + (1|sub), data=PVT,REML=TRUE)
pvtrslmm_tab<- anova(pvtrs_lm)
pvtslowestlm_tab <- anova(pvtslowrs_lm)
write_xlsx(pvtrslmm_tab,"GitStuff/mswake/SpreadsheetsnJASP/pvt_lmmanova.xlsx")
write_xlsx(pvtslowestlm_tab,"GitStuff/mswake/SpreadsheetsnJASP/pvt_slowestlmmanova.xlsx")
anova(pvtrsb_lm)
anova(pvtslowrs_lm)
anova(lapses_lm)
anova(pvtslowrsb_lm)
effectsize::eta_squared(pvtrs_lm, partial = TRUE) ### partial eta sq
effectsize::eta_squared(pvtslowrs_lm, partial = TRUE) ### partial eta sq
lapses_glmer <- glmer(Total_lapse ~ Time*Sex + Time*Weight + (1|sub), data=PVT, family=poisson(link="log"),control=glmerControl(optimizer="bobyqa"))
anova(lapses_glmer)
emmeans(lapses_glmer,pairwise~Sex)
